In [121]:
import numpy as np
import csv
from collections import defaultdict
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer

In [122]:
def sigmoid(x):
    return (1/(1+(np.exp(-x))))
def sigmoid_derivative(x):
    return x*(1-x)

In [123]:
trainarr = []
temp2=[]
trainoparr = []
csv_reader = csv.DictReader(open('ann.csv'))
for line in csv_reader:
    temp = []
    temp.append(float(line['sid']))
    temp.append(float(line['sentiment']))
    trainarr.append(temp)
    temp2.append(int(line['target']))
trainoparr.append(temp2)
training_inputs = np.array(trainarr)
training_outputs = np.array(trainoparr).T
np.random.seed(1)

synaptic_weights = 2 * np.random.random((2,1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]]


In [124]:
for iteration in range(2000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer,synaptic_weights))
    error = training_outputs - outputs
    adjustements = error * sigmoid_derivative(outputs)       
    synaptic_weights += np.dot(input_layer.T,adjustements)

print('Ouputs after training : ')
print(outputs)

Ouputs after training : 
[[9.99999921e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.95451673e-01]
 [1.00000000e+00]
 [9.99999995e-01]
 [9.99993433e-01]
 [9.99998216e-01]
 [9.99999990e-01]
 [9.99985383e-01]
 [9.99273347e-01]
 [1.00000000e+00]
 [9.92262333e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.99999993e-01]
 [9.99999624e-01]
 [9.99952456e-01]
 [5.09077389e-02]
 [8.42095017e-01]
 [9.99644466e-01]
 [1.00000000e+00]
 [9.99999917e-01]
 [3.89525206e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.99999999e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.00000000e+00]
 [7.67157305e-01]
 [9.99971656e-01]
 [9.82123789e-01]
 [9.99999994e-01]
 [6.59796044e-01]
 [9.99999888e-01]
 [9.96479881e-01]
 [9.99999717e-01]
 [9.99993307e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [5.74451751e-01]
 [1.00000000e+00]
 [9.60725229e-01]
 [9.99999379e-01]
 [9.99999668e-01]
 [9.99205365e-01]
 [1.39057878e-04]
 [2.14956063e-05]
 [4.61050447e-05]
 [1.73571619e-01]
 [2

In [125]:
print('Synaptic weights after Training')
print(synaptic_weights)

Synaptic weights after Training
[[31.12882403]
 [ 6.0397378 ]]


Our Training is Over now it's time for prediction.

In [126]:
word_freq = defaultdict(int)
text = "Luckily I don’t have to pay you for making me happy. I would have been bankrupt already if I had to!"
obj = TextBlob(text)
sentiment = obj.sentiment.polarity
tokenizer = RegexpTokenizer(r'\w+')
text_list = tokenizer.tokenize(text)
csv_reader = csv.DictReader(open('trainds.csv','r'))
sid = 0
for line in csv_reader:
    for text in text_list:
        if(line['words']==text):
            sid+=float(line['weights'])
temp = []
temp.append(sid)
temp.append(sentiment)
iarr = []
iarr.append(temp)
test_input = np.array(iarr)
test_output = sigmoid(np.dot(test_input,synaptic_weights))
print(test_output)

[[2.08849182e-05]]


In [129]:
prob = int(test_output*100)
print("The probability of the person having Sucidal Ideation is "+str(prob)+"% .")

The probability of the person having Sucidal Ideation is 0% .
